jaffle_shop:
    target: dev
    outputs:
        dev:
            type: redshift
            host: dbtredshiftcluster-lgmxqlhteoum.chgvhub6llhm.us-east-1.redshift.amazonaws.com
            user: dbtadmin
            password: Dbtadmin108!
            port: 5439
            dbname: dbtworkshop
            schema: jaffle_shop
            threads: 1
            keepalives_idle: 240 # default 240 seconds
            connect_timeout: 10 # default 10 seconds
            ra3_node: true